services:
  nginx:
    image: nginx:1.17
    restart: always
    volumes:
      - ./public:/app/public/
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./var/log/nginx/:/var/log/nginx
    ports:
      - '9999:80'
    depends_on:
      - php-fpm
    links:
      - php-fpm

  db:
    image: percona:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 3309:3306

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always

volumes:
  db-data:
